In [6]:
#pip install dlib
#pip install cmake
#pip install face_recognition

In [7]:
import face_recognition
import cv2
import numpy as np
import os

In [8]:
video_capture = cv2.VideoCapture(0)

In [9]:
image1 = face_recognition.load_image_file(os.path.abspath(r"C:\Projects\Python Projects\face recognition\images\dog.jpg"))
image1_face_encoding = face_recognition.face_encodings(image1)[0]

In [10]:
image2 = face_recognition.load_image_file(os.path.abspath(r"C:\Projects\Python Projects\face recognition\images\picture.jpg"))
image2_face_encoding = face_recognition.face_encodings(image2)[0]

In [11]:
image3 = face_recognition.load_image_file(os.path.abspath(r"C:\Projects\Python Projects\face recognition\images\guru prakash.jpg"))
image3_face_encoding = face_recognition.face_encodings(image3)[0]

In [12]:
known_face_encodings = [image1_face_encoding,image2_face_encoding,image3_face_encoding]
known_face_names = ["dog","Hananya","guru prakash"]

In [13]:
face_locations = []
face_encodings = []
face_names = []
process_this_frame = True

In [14]:
while True:
    ret, frame = video_capture.read()
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)
    rgb_small_frame = small_frame[:, :, ::-1]
    print(rgb_small_frame)
    if process_this_frame:
        face_locations = face_recognition.face_locations(rgb_small_frame)
        face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)

        face_names = []
        for face_encoding in face_encodings:
            matches = face_recognition.compare_faces(known_face_encodings, face_encoding, tolerance=0.6)
            name = "Unknown"
            face_distances = face_recognition.face_distance(known_face_encodings, face_encoding)
            best_match_index = np.argmin(face_distances)
            if matches[best_match_index]:
                name = known_face_names[best_match_index]
            face_names.append(name)

    process_this_frame = not process_this_frame
    print ("Face detected -- {}".format(face_names))
    for (top, right, bottom, left), name in zip(face_locations, face_names):
        top *= 4
        right *= 4
        bottom *= 4
        left *= 4
        cv2.rectangle(frame, (left, top), (right, bottom), (0, 255, 0), 2)
        cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (0, 255, 0), cv2.FILLED)
        font = cv2.FONT_HERSHEY_DUPLEX
        cv2.putText(frame, name, (left + 6, bottom - 6), font, 0.6, (255, 255, 255), 1)

    cv2.imshow('Video', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()


[[[ 86  95  82]
  [ 90  98  92]
  [ 94  94  85]
  ...
  [123 113 113]
  [128 120 112]
  [131 114 110]]

 [[ 87  99  89]
  [ 89 100  86]
  [ 88 100  86]
  ...
  [131 126 110]
  [129 119 104]
  [130 115 105]]

 [[ 83  99  84]
  [ 88 101  87]
  [ 86  98  85]
  ...
  [ 70  54  56]
  [ 76  65  63]
  [ 88  81  79]]

 ...

 [[146 180 164]
  [149 180 168]
  [148 178 167]
  ...
  [ 75  76  57]
  [ 73  73  53]
  [ 74  77  56]]

 [[149 175 168]
  [150 177 168]
  [149 179 168]
  ...
  [ 75  76  57]
  [ 76  74  56]
  [ 74  68  56]]

 [[151 179 162]
  [148 179 165]
  [146 178 166]
  ...
  [ 77  73  56]
  [ 76  75  58]
  [ 74  76  58]]]
Face detected -- []
[[[ 91 101  75]
  [ 91  92  87]
  [ 89 102  81]
  ...
  [129 118 115]
  [129 114 109]
  [130 112 104]]

 [[ 91  99  79]
  [ 90  95  82]
  [ 92  97  87]
  ...
  [135 124 112]
  [133 122 109]
  [130 115 110]]

 [[ 93  92  89]
  [ 92  97  87]
  [ 88  96  84]
  ...
  [ 72  55  64]
  [ 78  64  67]
  [ 89  79  78]]

 ...

 [[149 179 172]
  [150 176 168]


Face detected -- ['guru prakash']
[[[ 95 103  77]
  [ 96 101  88]
  [ 94  97  96]
  ...
  [141 112 114]
  [134 109 111]
  [130 115 107]]

 [[ 97  97  87]
  [ 95  99  87]
  [ 94 101  87]
  ...
  [137 120 116]
  [132 115 113]
  [136 117 112]]

 [[ 97  96  89]
  [ 97  97  89]
  [ 95  98  86]
  ...
  [ 80  57  66]
  [ 80  61  67]
  [ 90  75  82]]

 ...

 [[160 175 168]
  [156 176 168]
  [157 177 171]
  ...
  [113 109 155]
  [114 110 155]
  [118 111 161]]

 [[156 176 166]
  [156 177 169]
  [156 175 168]
  ...
  [112 105 151]
  [112 105 152]
  [113 107 154]]

 [[155 174 168]
  [155 176 169]
  [154 175 168]
  ...
  [111 106 153]
  [111 103 150]
  [114 109 149]]]
Face detected -- ['guru prakash']
[[[ 95 105  82]
  [102  97  89]
  [103  96  85]
  ...
  [136 113 112]
  [126 115 114]
  [132 116 113]]

 [[101  95  86]
  [100  97  83]
  [100  97  87]
  ...
  [139 120 112]
  [134 116 109]
  [134 117 111]]

 [[102  93  93]
  [100  96  87]
  [100  97  86]
  ...
  [ 74  54  64]
  [ 83  62  70]
  [100  

[[[100  93  93]
  [ 99  98  88]
  [105  97  95]
  ...
  [133 116 113]
  [137 112 109]
  [134 112 118]]

 [[104  95  88]
  [100  94  86]
  [ 99  96  88]
  ...
  [141 122 115]
  [138 118 111]
  [140 114 111]]

 [[ 96  98  97]
  [100  94  91]
  [103  95  91]
  ...
  [ 80  53  64]
  [ 85  63  70]
  [102  80  88]]

 ...

 [[165 171 166]
  [160 176 171]
  [159 176 170]
  ...
  [ 41  18  47]
  [ 47  24  54]
  [ 52  30  58]]

 [[164 170 166]
  [161 173 168]
  [158 175 169]
  ...
  [ 44  19  55]
  [ 52  22  58]
  [ 58  28  63]]

 [[160 174 168]
  [156 175 166]
  [160 178 171]
  ...
  [ 47  27  53]
  [ 51  31  60]
  [ 47  34  67]]]
Face detected -- []
[[[ 82  90  68]
  [ 83  82  69]
  [ 85  83  72]
  ...
  [122 101  89]
  [123  97  96]
  [112 100 102]]

 [[ 80  88  64]
  [ 81  84  68]
  [ 83  85  71]
  ...
  [123 106  92]
  [122 106  94]
  [116 104  97]]

 [[ 77  87  79]
  [ 81  85  72]
  [ 82  86  71]
  ...
  [ 56  37  47]
  [ 66  52  55]
  [ 78  67  69]]

 ...

 [[134 164 151]
  [142 162 155]


Face detected -- []
[[[ 79  84  74]
  [ 82  84  80]
  [ 82  90  67]
  ...
  [123  97 107]
  [118  97  97]
  [128  94  94]]

 [[ 78  86  74]
  [ 82  85  75]
  [ 83  85  73]
  ...
  [121 110  98]
  [122 113 102]
  [117 105  95]]

 [[ 83  88  70]
  [ 80  81  72]
  [ 81  83  72]
  ...
  [ 56  39  45]
  [ 61  46  49]
  [ 78  66  61]]

 ...

 [[146 162 157]
  [145 163 157]
  [144 162 156]
  ...
  [110 111 148]
  [ 94  94 123]
  [ 84  80  98]]

 [[140 159 162]
  [145 161 157]
  [146 162 157]
  ...
  [109 106 148]
  [105 106 142]
  [ 87  90 113]]

 [[147 158 150]
  [143 162 156]
  [142 163 155]
  ...
  [106 101 147]
  [107 106 146]
  [ 98  98 128]]]
Face detected -- []
[[[ 79  84  74]
  [ 82  84  80]
  [ 82  90  67]
  ...
  [123  97 107]
  [118  97  97]
  [128  94  94]]

 [[ 78  86  74]
  [ 82  85  75]
  [ 83  85  73]
  ...
  [121 110  98]
  [122 113 102]
  [117 105  95]]

 [[ 83  88  70]
  [ 80  81  72]
  [ 81  83  72]
  ...
  [ 56  39  45]
  [ 61  46  49]
  [ 78  66  61]]

 ...

 [[146 162 1

Face detected -- []
[[[ 95  83  73]
  [ 79  84  74]
  [ 95  81  83]
  ...
  [119 102 103]
  [118 101  99]
  [119  99 102]]

 [[ 77  86  75]
  [ 80  86  73]
  [ 83  85  75]
  ...
  [125 111 103]
  [125 109 104]
  [120 102 100]]

 [[ 78  89  86]
  [ 79  85  73]
  [ 84  87  74]
  ...
  [ 60  44  53]
  [ 64  45  50]
  [ 82  58  67]]

 ...

 [[142 164 158]
  [142 163 156]
  [141 162 154]
  ...
  [ 59  58  34]
  [ 55  57  33]
  [ 56  61  36]]

 [[147 158 156]
  [141 160 154]
  [141 163 155]
  ...
  [ 58  57  33]
  [ 59  60  36]
  [ 60  59  36]]

 [[139 160 158]
  [142 159 154]
  [144 161 154]
  ...
  [ 60  59  30]
  [ 58  60  30]
  [ 57  56  26]]]
Face detected -- []
[[[ 95  83  73]
  [ 79  84  74]
  [ 95  81  83]
  ...
  [119 102 103]
  [118 101  99]
  [119  99 102]]

 [[ 77  86  75]
  [ 80  86  73]
  [ 83  85  75]
  ...
  [125 111 103]
  [125 109 104]
  [120 102 100]]

 [[ 78  89  86]
  [ 79  85  73]
  [ 84  87  74]
  ...
  [ 60  44  53]
  [ 64  45  50]
  [ 82  58  67]]

 ...

 [[142 164 1

[[[ 80  90  75]
  [ 76  94  65]
  [ 81  90  75]
  ...
  [119  99  96]
  [118 100 105]
  [123  97 104]]

 [[ 87  87  68]
  [ 85  87  77]
  [ 83  85  80]
  ...
  [126 111 100]
  [125 109 103]
  [124 100 100]]

 [[ 83  83  76]
  [ 82  82  74]
  [ 83  83  75]
  ...
  [ 66  42  48]
  [ 66  39  49]
  [ 84  61  69]]

 ...

 [[150 161 152]
  [144 162 156]
  [141 163 156]
  ...
  [ 59  54  32]
  [ 61  59  38]
  [ 55  57  34]]

 [[143 163 152]
  [140 160 153]
  [142 164 155]
  ...
  [ 56  56  35]
  [ 61  59  39]
  [ 60  53  38]]

 [[143 163 151]
  [143 163 152]
  [143 161 151]
  ...
  [ 57  55  34]
  [ 57  55  32]
  [ 62  56  28]]]
Face detected -- []
[[[ 80  90  75]
  [ 76  94  65]
  [ 81  90  75]
  ...
  [119  99  96]
  [118 100 105]
  [123  97 104]]

 [[ 87  87  68]
  [ 85  87  77]
  [ 83  85  80]
  ...
  [126 111 100]
  [125 109 103]
  [124 100 100]]

 [[ 83  83  76]
  [ 82  82  74]
  [ 83  83  75]
  ...
  [ 66  42  48]
  [ 66  39  49]
  [ 84  61  69]]

 ...

 [[150 161 152]
  [144 162 156]


Face detected -- []
[[[ 84  95  91]
  [ 91  95  85]
  [ 93  98  79]
  ...
  [132 114  99]
  [134 112 103]
  [135 109 113]]

 [[ 87  96  88]
  [ 88  92  82]
  [ 93  95  84]
  ...
  [139 123 111]
  [137 121 109]
  [132 118 109]]

 [[ 86  95  79]
  [ 90  92  81]
  [ 90  93  80]
  ...
  [ 72  50  59]
  [ 74  55  60]
  [ 89  71  73]]

 ...

 [[155 174 171]
  [156 175 169]
  [155 173 167]
  ...
  [ 68  67  40]
  [ 72  69  45]
  [ 74  70  50]]

 [[148 174 169]
  [153 173 168]
  [152 173 168]
  ...
  [ 74  65  40]
  [ 73  65  42]
  [ 71  62  44]]

 [[154 173 162]
  [153 173 166]
  [154 174 167]
  ...
  [ 74  66  45]
  [ 73  65  41]
  [ 74  64  40]]]
Face detected -- []
[[[ 98  90  86]
  [ 95  96  88]
  [ 91  93  86]
  ...
  [135 114 113]
  [129 110 116]
  [138 106 105]]

 [[ 92  95  83]
  [ 91  92  86]
  [ 93  94  89]
  ...
  [135 120 112]
  [136 120 113]
  [133 113 109]]

 [[ 88  95  79]
  [ 90  93  83]
  [ 93  95  87]
  ...
  [ 67  48  57]
  [ 71  52  58]
  [ 88  65  73]]

 ...

 [[154 176 1

Face detected -- []
[[[ 89  93  83]
  [ 94  94  83]
  [ 95  94  85]
  ...
  [127 111 105]
  [128 109 103]
  [136 109 108]]

 [[ 95  94  83]
  [ 92  94  81]
  [ 93  96  84]
  ...
  [135 119 107]
  [137 120 110]
  [130 115 109]]

 [[ 87  94  90]
  [ 91  94  85]
  [ 91  94  83]
  ...
  [ 69  48  58]
  [ 75  56  61]
  [ 85  76  74]]

 ...

 [[153 175 171]
  [154 175 170]
  [153 173 167]
  ...
  [ 78  61  44]
  [ 76  64  44]
  [ 75  65  48]]

 [[157 173 170]
  [152 174 170]
  [153 175 170]
  ...
  [ 76  62  42]
  [ 76  63  39]
  [ 75  65  39]]

 [[153 175 168]
  [154 176 166]
  [154 176 168]
  ...
  [ 70  57  42]
  [ 71  61  43]
  [ 71  64  46]]]
Face detected -- []
[[[ 92  95  91]
  [ 97  92  87]
  [102  92  89]
  ...
  [142 107 108]
  [132 106 109]
  [125 115 106]]

 [[ 90  97  76]
  [ 93  94  79]
  [ 94  95  83]
  ...
  [142 120 111]
  [136 116 105]
  [128 116 104]]

 [[ 86  94  85]
  [ 91  94  82]
  [ 90  93  81]
  ...
  [ 70  51  56]
  [ 77  59  60]
  [ 90  70  73]]

 ...

 [[157 173 1

Face detected -- []
[[[ 85  96  82]
  [ 94  95  77]
  [ 94  94  86]
  ...
  [134 110 113]
  [134 107 110]
  [130 109 111]]

 [[ 90  92  86]
  [ 89  98  86]
  [ 89  96  86]
  ...
  [137 121 113]
  [136 119 110]
  [132 114 107]]

 [[ 95  90  80]
  [ 91  93  84]
  [ 90  91  87]
  ...
  [ 69  46  63]
  [ 75  54  63]
  [ 89  70  68]]

 ...

 [[156 174 168]
  [156 175 168]
  [155 176 167]
  ...
  [ 77  69  50]
  [ 77  67  51]
  [ 74  61  53]]

 [[157 174 168]
  [156 175 168]
  [158 176 170]
  ...
  [ 76  66  50]
  [ 77  64  48]
  [ 77  62  47]]

 [[159 173 169]
  [155 176 166]
  [156 177 166]
  ...
  [ 76  65  55]
  [ 73  63  52]
  [ 72  69  47]]]
Face detected -- []
[[[ 81 100  88]
  [ 84  99  83]
  [ 93  95  86]
  ...
  [140 108 109]
  [128 108 114]
  [129 108 108]]

 [[ 93  88  88]
  [ 91  95  87]
  [ 91  96  83]
  ...
  [135 117 108]
  [135 116 112]
  [133 112 113]]

 [[ 85  93  91]
  [ 87  97  88]
  [ 90  98  87]
  ...
  [ 69  49  58]
  [ 76  55  59]
  [ 85  70  70]]

 ...

 [[155 175 1

Face detected -- ['guru prakash']
[[[ 90  98  92]
  [ 84  94  84]
  [ 92 101  78]
  ...
  [133 113 111]
  [127 112 112]
  [132 109 117]]

 [[ 88  95  93]
  [ 92  93  89]
  [ 96  97  89]
  ...
  [134 118 110]
  [135 120 109]
  [132 114 109]]

 [[ 92  92  93]
  [ 91  92  87]
  [ 91  93  87]
  ...
  [ 68  49  56]
  [ 70  53  55]
  [ 82  72  62]]

 ...

 [[156 176 166]
  [155 176 167]
  [156 175 168]
  ...
  [ 78  74  61]
  [ 74  69  60]
  [ 70  68  62]]

 [[155 173 165]
  [156 175 165]
  [156 175 167]
  ...
  [ 73  74  64]
  [ 74  74  61]
  [ 79  72  54]]

 [[159 172 168]
  [154 174 164]
  [154 176 165]
  ...
  [ 74  75  59]
  [ 73  76  59]
  [ 73  69  59]]]
Face detected -- ['guru prakash']
[[[ 96  93  82]
  [ 94  94  87]
  [ 96  98  84]
  ...
  [132 109 114]
  [124 111 110]
  [134 106 106]]

 [[ 91  96  83]
  [ 94  97  84]
  [ 93  97  83]
  ...
  [137 122 109]
  [133 121 109]
  [130 116 110]]

 [[ 95  96  86]
  [ 91  95  86]
  [ 89  95  83]
  ...
  [ 66  48  56]
  [ 72  55  62]
  [ 86  

Face detected -- []
[[[ 98  95  86]
  [ 92  98  82]
  [ 93 101  80]
  ...
  [135 112 109]
  [123 109 110]
  [132 112 111]]

 [[ 96  97  75]
  [ 93  99  83]
  [ 93  96  86]
  ...
  [133 118 106]
  [136 119 108]
  [132 112 105]]

 [[ 95  97  84]
  [ 96  97  83]
  [ 94  95  85]
  ...
  [ 68  47  57]
  [ 74  51  57]
  [ 87  66  67]]

 ...

 [[158 169 168]
  [156 174 168]
  [154 175 168]
  ...
  [ 76  65  49]
  [ 75  65  53]
  [ 75  62  56]]

 [[153 172 166]
  [154 174 167]
  [154 174 167]
  ...
  [ 74  63  53]
  [ 76  65  56]
  [ 76  68  52]]

 [[150 175 166]
  [153 176 166]
  [152 173 165]
  ...
  [ 77  66  53]
  [ 78  65  51]
  [ 76  63  49]]]
Face detected -- []
[[[ 90  96  96]
  [ 92  98  85]
  [101  95  83]
  ...
  [132 114 109]
  [129 112 112]
  [134 111 114]]

 [[ 95  93  86]
  [ 93  94  86]
  [ 94  95  86]
  ...
  [132 116 104]
  [133 116 108]
  [131 113 110]]

 [[ 86 100  84]
  [ 89  95  81]
  [ 90  95  84]
  ...
  [ 72  58  65]
  [ 77  57  67]
  [ 94  75  84]]

 ...

 [[155 173 1

Face detected -- ['guru prakash']
[[[103  91  83]
  [ 91  94  89]
  [ 98  95  83]
  ...
  [133 110 111]
  [122 114 105]
  [131 105 108]]

 [[ 94  93  84]
  [ 90  92  83]
  [ 89  94  81]
  ...
  [122 109 103]
  [133 118 111]
  [129 110 105]]

 [[ 98  89  84]
  [ 92  92  84]
  [ 90  93  84]
  ...
  [ 66  45  61]
  [ 66  46  60]
  [ 73  51  61]]

 ...

 [[152 173 168]
  [155 176 168]
  [154 176 168]
  ...
  [126 129 172]
  [127 127 168]
  [121 117 162]]

 [[158 173 168]
  [158 173 166]
  [156 174 166]
  ...
  [125 122 167]
  [129 125 170]
  [123 123 169]]

 [[152 172 167]
  [154 172 166]
  [157 174 168]
  ...
  [118 111 158]
  [128 120 168]
  [132 126 176]]]
Face detected -- ['guru prakash']
[[[ 95  94  80]
  [ 95  92  85]
  [102  92  84]
  ...
  [133 114 107]
  [129 109 103]
  [130 107 106]]

 [[ 81  97  80]
  [ 90  90  76]
  [ 93  92  78]
  ...
  [126 111 104]
  [134 118 111]
  [130 110 105]]

 [[ 85  93  84]
  [ 90  93  82]
  [ 92  94  84]
  ...
  [ 65  43  59]
  [ 69  46  61]
  [ 72  

Face detected -- ['guru prakash']
[[[ 91  95  86]
  [ 88  98  90]
  [ 94  92  86]
  ...
  [122 114 108]
  [122 114 106]
  [134 111 100]]

 [[ 88  98  87]
  [ 88  93  83]
  [ 93  95  86]
  ...
  [124 107 103]
  [136 120 110]
  [129 112  95]]

 [[ 95  93  90]
  [ 94  95  84]
  [ 91  93  81]
  ...
  [ 69  43  57]
  [ 70  41  52]
  [ 79  50  53]]

 ...

 [[154 176 175]
  [155 174 169]
  [155 175 168]
  ...
  [120 117 165]
  [125 123 168]
  [128 125 168]]

 [[155 175 169]
  [156 175 167]
  [155 176 164]
  ...
  [112 108 157]
  [123 122 170]
  [124 126 170]]

 [[156 173 169]
  [154 173 165]
  [156 176 166]
  ...
  [114 111 157]
  [114 112 158]
  [126 125 170]]]
Face detected -- ['guru prakash']
[[[ 94  89  84]
  [ 93  93  83]
  [ 99  93  89]
  ...
  [139 111 105]
  [130 107 110]
  [126 109 112]]

 [[ 92  94  91]
  [ 93  94  87]
  [ 94  96  86]
  ...
  [123 111 102]
  [135 121 111]
  [128 110 110]]

 [[ 92  94  80]
  [ 92  95  83]
  [ 91  93  81]
  ...
  [ 67  48  61]
  [ 67  46  57]
  [ 69  

[[[ 90  88  84]
  [ 83  92  73]
  [ 88  93  77]
  ...
  [134 108 107]
  [132 108  97]
  [124 110 103]]

 [[ 84  90  72]
  [ 87  89  78]
  [ 89  90  80]
  ...
  [123 106  96]
  [133 117 106]
  [127 110 103]]

 [[ 83  91  73]
  [ 84  86  77]
  [ 88  90  82]
  ...
  [ 63  44  55]
  [ 64  42  56]
  [ 69  44  62]]

 ...

 [[ 67  43  58]
  [ 61  41  60]
  [ 53  38  58]
  ...
  [ 97  93 131]
  [ 96  95 132]
  [ 97  95 134]]

 [[ 57  48  50]
  [ 60  45  57]
  [ 61  47  61]
  ...
  [ 92  93 129]
  [ 92  92 130]
  [ 92  89 132]]

 [[ 47  50  58]
  [ 53  40  52]
  [ 58  37  54]
  ...
  [ 91  95 131]
  [ 88  92 127]
  [ 84  85 122]]]
Face detected -- []
[[[ 90  88  84]
  [ 83  92  73]
  [ 88  93  77]
  ...
  [134 108 107]
  [132 108  97]
  [124 110 103]]

 [[ 84  90  72]
  [ 87  89  78]
  [ 89  90  80]
  ...
  [123 106  96]
  [133 117 106]
  [127 110 103]]

 [[ 83  91  73]
  [ 84  86  77]
  [ 88  90  82]
  ...
  [ 63  44  55]
  [ 64  42  56]
  [ 69  44  62]]

 ...

 [[ 67  43  58]
  [ 61  41  60]


Face detected -- ['guru prakash']
[[[ 82  98  65]
  [ 92  91  58]
  [ 99  94  57]
  ...
  [128 121  79]
  [125 116  77]
  [126 112  87]]

 [[ 92  89  67]
  [ 89  94  64]
  [ 88  93  64]
  ...
  [120 112  78]
  [127 123  84]
  [125 114  80]]

 [[ 91  93  64]
  [ 88  93  64]
  [ 89  94  63]
  ...
  [ 65  46  33]
  [ 69  47  33]
  [ 74  50  32]]

 ...

 [[ 30  33  32]
  [ 32  29  31]
  [ 31  27  28]
  ...
  [ 96  94 112]
  [ 97  97 114]
  [ 97  93 108]]

 [[ 23  37  26]
  [ 34  32  24]
  [ 39  31  25]
  ...
  [ 91  95 111]
  [ 95  97 113]
  [ 97  96 107]]

 [[ 35  34  28]
  [ 37  31  24]
  [ 36  27  26]
  ...
  [ 89  96 107]
  [ 88  93 105]
  [ 85  87  99]]]
Face detected -- ['guru prakash']
[[[ 89  95  62]
  [ 87  96  60]
  [ 90  93  59]
  ...
  [132 116  85]
  [132 112  81]
  [129 110  92]]

 [[ 86  96  50]
  [ 86  96  54]
  [ 90  97  59]
  ...
  [123 111  79]
  [131 118  85]
  [128 110  79]]

 [[ 84  91  67]
  [ 89  93  61]
  [ 89  90  55]
  ...
  [ 58  49  32]
  [ 64  51  34]
  [ 69  

Face detected -- []
[[[ 80  99  52]
  [ 89  93  53]
  [ 94  97  46]
  ...
  [133 119  78]
  [124 116  75]
  [133 110  76]]

 [[ 84  97  53]
  [ 88  96  49]
  [ 86  96  51]
  ...
  [119 108  68]
  [131 118  78]
  [128 114  73]]

 [[ 88  93  57]
  [ 88  95  54]
  [ 88  96  55]
  ...
  [ 64  45  31]
  [ 66  45  31]
  [ 74  51  34]]

 ...

 [[ 62  57  37]
  [ 61  54  35]
  [ 58  50  32]
  ...
  [ 95  98  99]
  [ 96  96  97]
  [ 96  91  95]]

 [[ 57  52  37]
  [ 55  51  29]
  [ 57  48  30]
  ...
  [ 93  95 100]
  [ 91  90  96]
  [ 88  86  94]]

 [[ 52  45  30]
  [ 50  39  25]
  [ 52  44  28]
  ...
  [ 88  90  89]
  [ 89  89  90]
  [ 88  87  87]]]
Face detected -- []
[[[ 98  93  39]
  [ 91  96  42]
  [ 93 100  50]
  ...
  [130 119  78]
  [126 114  71]
  [128 116  69]]

 [[ 86  96  52]
  [ 88  94  49]
  [ 89  96  50]
  ...
  [118 109  67]
  [131 120  78]
  [126 114  75]]

 [[ 80  97  57]
  [ 88  96  49]
  [ 86  98  47]
  ...
  [ 62  51  21]
  [ 67  53  25]
  [ 72  55  30]]

 ...

 [[ 50  46  

Face detected -- []
[[[ 88  97  52]
  [ 91  93  38]
  [ 90  96  48]
  ...
  [131 122  69]
  [127 114  74]
  [130 109  70]]

 [[ 84  98  56]
  [ 87  96  45]
  [ 87  94  41]
  ...
  [117 108  62]
  [127 124  73]
  [122 116  74]]

 [[ 84  91  56]
  [ 85  94  50]
  [ 88  95  51]
  ...
  [ 62  46  20]
  [ 64  51  25]
  [ 59  55  26]]

 ...

 [[ 61  34  39]
  [ 69  38  42]
  [ 74  42  42]
  ...
  [ 96  99  97]
  [ 94  95  96]
  [ 89  91  91]]

 [[ 60  30  35]
  [ 66  40  36]
  [ 70  39  37]
  ...
  [ 95  95  94]
  [ 94  94  94]
  [ 87  86  87]]

 [[ 66  34  36]
  [ 59  34  30]
  [ 65  36  37]
  ...
  [ 90  90  90]
  [ 89  89  88]
  [ 88  87  88]]]
Face detected -- []
[[[ 70  81  37]
  [ 76  78  42]
  [ 78  77  45]
  ...
  [120 124  67]
  [124 113  70]
  [125 116  73]]

 [[ 63  77  22]
  [ 72  76  35]
  [ 76  76  39]
  ...
  [119 114  65]
  [129 123  72]
  [125 117  68]]

 [[ 62  77  42]
  [ 73  79  40]
  [ 69  77  41]
  ...
  [ 60  47  21]
  [ 64  52  24]
  [ 67  58  25]]

 ...

 [[ 64  56 1

Face detected -- []
[[[ 85  99  47]
  [ 91  92  49]
  [ 97  98  43]
  ...
  [127 119  77]
  [130 111  75]
  [126 115  76]]

 [[ 89  99  54]
  [ 89  98  47]
  [ 89  97  47]
  ...
  [119 109  67]
  [131 120  76]
  [124 117  68]]

 [[ 89  96  55]
  [ 90  96  47]
  [ 88  97  46]
  ...
  [ 65  51  29]
  [ 66  50  21]
  [ 69  53  19]]

 ...

 [[148 172 123]
  [148 172 118]
  [146 172 115]
  ...
  [ 94  97  96]
  [ 96  94  95]
  [ 94  85  88]]

 [[149 174 121]
  [147 174 119]
  [145 173 116]
  ...
  [ 96  97  97]
  [ 94  94  93]
  [ 88  90  87]]

 [[150 172 120]
  [148 172 116]
  [148 171 114]
  ...
  [ 91  93  89]
  [ 90  91  86]
  [ 87  87  82]]]
Face detected -- []
[[[ 91  92  50]
  [ 88  95  49]
  [ 94  95  45]
  ...
  [131 118  70]
  [134 115  65]
  [127 116  66]]

 [[ 89  98  42]
  [ 89  97  45]
  [ 90  97  44]
  ...
  [120 111  65]
  [132 122  73]
  [127 117  70]]

 [[ 84  96  48]
  [ 89  93  47]
  [ 92  96  49]
  ...
  [ 63  50  28]
  [ 63  47  23]
  [ 69  55  28]]

 ...

 [[150 173 1

[[[ 94  98  51]
  [ 91  96  42]
  [ 89  98  42]
  ...
  [129 116  69]
  [126 118  70]
  [126 114  70]]

 [[ 90  97  45]
  [ 90  95  46]
  [ 88  96  45]
  ...
  [120 109  60]
  [131 121  72]
  [127 114  73]]

 [[ 90  97  54]
  [ 91  96  48]
  [ 89  97  47]
  ...
  [ 61  48  22]
  [ 65  47  27]
  [ 72  48  33]]

 ...

 [[145 171 114]
  [148 173 116]
  [145 169 112]
  ...
  [ 99  98  96]
  [ 95  95  95]
  [ 91  93  92]]

 [[144 170 115]
  [145 171 114]
  [146 170 111]
  ...
  [ 95  95  95]
  [ 95  98  96]
  [ 90  95  87]]

 [[147 169 116]
  [143 169 115]
  [147 171 115]
  ...
  [ 97  96  94]
  [ 93  94  90]
  [ 88  93  89]]]
Face detected -- []
[[[ 91  95  48]
  [ 87 100  44]
  [ 94  97  50]
  ...
  [137 119  73]
  [131 114  70]
  [130 112  68]]

 [[ 91  97  46]
  [ 89  97  43]
  [ 89  98  45]
  ...
  [121 112  66]
  [133 122  71]
  [129 113  66]]

 [[ 88  96  45]
  [ 88  97  45]
  [ 87  95  46]
  ...
  [ 66  49  26]
  [ 62  49  20]
  [ 71  56  26]]

 ...

 [[145 173 113]
  [144 171 109]


Face detected -- []
[[[ 89  96  46]
  [ 85  94  49]
  [ 93  99  52]
  ...
  [136 118  71]
  [127 109  71]
  [126 116  68]]

 [[ 87  95  57]
  [ 89  97  44]
  [ 88  98  42]
  ...
  [118 113  63]
  [130 123  72]
  [125 116  63]]

 [[ 89  96  38]
  [ 89  98  44]
  [ 89  97  44]
  ...
  [ 64  50  22]
  [ 63  50  17]
  [ 70  59  18]]

 ...

 [[149 172 113]
  [145 174 114]
  [142 172 113]
  ...
  [ 97  99  96]
  [ 95  97  92]
  [ 96  93  88]]

 [[143 176 113]
  [144 174 112]
  [144 174 112]
  ...
  [ 94  98  95]
  [ 92 100  92]
  [ 88  99  87]]

 [[149 174 117]
  [148 174 112]
  [148 175 113]
  ...
  [ 93  96  93]
  [ 90  95  89]
  [ 88  96  92]]]
Face detected -- []
[[[ 92  97  40]
  [ 83 103  45]
  [ 82  99  40]
  ...
  [134 119  61]
  [121 115  70]
  [124 113  69]]

 [[ 93  94  42]
  [ 90  98  43]
  [ 90  99  43]
  ...
  [120 109  61]
  [130 119  71]
  [128 112  70]]

 [[ 90  98  48]
  [ 85  99  45]
  [ 86  99  45]
  ...
  [ 67  50  22]
  [ 65  49  20]
  [ 70  54  27]]

 ...

 [[143 173 1

Face detected -- []
[[[ 90  96  40]
  [ 94  94  45]
  [ 92  97  47]
  ...
  [131 115  71]
  [133 111  64]
  [121 115  72]]

 [[ 96  94  46]
  [ 91  97  42]
  [ 90  98  40]
  ...
  [124 112  60]
  [131 122  68]
  [120 118  66]]

 [[ 83  98  49]
  [ 89  97  41]
  [ 89  97  39]
  ...
  [ 67  49  18]
  [ 68  52  23]
  [ 69  54  24]]

 ...

 [[143 168 110]
  [140 170 106]
  [137 164 107]
  ...
  [ 99 101  95]
  [ 96 101  94]
  [ 92  95  92]]

 [[145 170 112]
  [141 172 112]
  [139 170 112]
  ...
  [ 95  96  93]
  [ 95  97  92]
  [ 93  94  86]]

 [[139 173 115]
  [141 170 110]
  [144 170 111]
  ...
  [ 95  98  92]
  [ 89  91  86]
  [ 87  95  90]]]
Face detected -- []
[[[ 85  98  44]
  [ 90  96  42]
  [ 97  96  54]
  ...
  [126 121  70]
  [125 116  68]
  [129 115  68]]

 [[ 89  96  42]
  [ 89  98  46]
  [ 89  98  47]
  ...
  [119 113  63]
  [129 123  71]
  [126 116  70]]

 [[ 89  95  48]
  [ 88  97  46]
  [ 86  98  44]
  ...
  [ 61  48  22]
  [ 65  52  21]
  [ 72  55  17]]

 ...

 [[147 171 1

Face detected -- []
[[[ 91  94  47]
  [ 87  97  41]
  [ 88 102  40]
  ...
  [121 119  67]
  [122 110  69]
  [127 118  69]]

 [[ 89  95  50]
  [ 87  96  42]
  [ 89  98  42]
  ...
  [119 111  62]
  [130 124  74]
  [127 114  67]]

 [[ 85 101  46]
  [ 88  98  43]
  [ 88  97  43]
  ...
  [ 61  48  16]
  [ 64  49  19]
  [ 68  54  28]]

 ...

 [[136 165 115]
  [111 132  84]
  [ 70  80  41]
  ...
  [ 95 102  95]
  [ 91 100  93]
  [ 89  94  90]]

 [[141 166 109]
  [140 165 105]
  [124 148  92]
  ...
  [ 96  97  91]
  [ 96  98  93]
  [ 89  90  87]]

 [[144 167 105]
  [143 169 108]
  [139 165 107]
  ...
  [ 94  95  90]
  [ 93  95  88]
  [ 87  93  85]]]
Face detected -- []
[[[ 94  94  49]
  [ 96  93  45]
  [ 92  99  46]
  ...
  [131 120  74]
  [123 118  67]
  [128 111  72]]

 [[ 96  96  35]
  [ 91  97  41]
  [ 88  98  40]
  ...
  [117 107  61]
  [134 126  75]
  [127 114  67]]

 [[ 93  92  47]
  [ 90  98  47]
  [ 89  98  45]
  ...
  [ 66  48  29]
  [ 70  50  27]
  [ 73  53  24]]

 ...

 [[102 123  

Face detected -- []
[[[ 97  90  52]
  [ 89  97  46]
  [ 90  98  48]
  ...
  [134 116  74]
  [126 115  68]
  [121 115  69]]

 [[ 89  91  49]
  [ 88  95  50]
  [ 86  96  46]
  ...
  [121 113  63]
  [128 125  72]
  [119 117  73]]

 [[ 93  96  49]
  [ 87  95  52]
  [ 88  96  52]
  ...
  [ 57  49  17]
  [ 60  57  24]
  [ 69  60  33]]

 ...

 [[149 165 111]
  [144 169 109]
  [139 164 109]
  ...
  [ 99 101  98]
  [ 97  97  94]
  [ 94  95  88]]

 [[143 170 115]
  [144 170 110]
  [140 168 107]
  ...
  [ 97  98  94]
  [ 97  98  92]
  [ 94  96  88]]

 [[148 169 105]
  [144 170 110]
  [143 170 110]
  ...
  [ 99  99  94]
  [ 90  91  87]
  [ 93  91  89]]]
Face detected -- []
[[[ 96  97  37]
  [ 87  99  42]
  [ 88 102  47]
  ...
  [134 118  68]
  [133 114  62]
  [136 108  66]]

 [[ 89  97  41]
  [ 90  98  45]
  [ 88  97  45]
  ...
  [122 112  63]
  [133 122  70]
  [129 114  68]]

 [[ 91  92  55]
  [ 89  94  47]
  [ 90  96  44]
  ...
  [ 64  51  16]
  [ 69  54  23]
  [ 70  54  24]]

 ...

 [[153 168 1

Face detected -- []
[[[ 90  95  46]
  [ 91  98  44]
  [ 89 102  36]
  ...
  [125 121  71]
  [129 113  65]
  [123 113  68]]

 [[ 85  99  44]
  [ 89  99  43]
  [ 88  98  43]
  ...
  [120 111  61]
  [130 120  70]
  [127 117  66]]

 [[ 85 100  39]
  [ 87  98  40]
  [ 89  97  46]
  ...
  [ 68  51  25]
  [ 62  47  17]
  [ 66  58  20]]

 ...

 [[151 171 114]
  [148 176 113]
  [147 176 112]
  ...
  [ 93  93  85]
  [ 89  91  82]
  [ 87  87  85]]

 [[143 176 118]
  [146 176 114]
  [146 176 113]
  ...
  [ 95  93  87]
  [ 93  94  83]
  [ 88  90  81]]

 [[151 172 116]
  [147 175 116]
  [147 176 113]
  ...
  [ 93  94  85]
  [ 86  87  79]
  [ 89  91  84]]]
Face detected -- []
[[[ 87  97  44]
  [ 94  95  44]
  [ 94  96  52]
  ...
  [129 122  73]
  [127 117  76]
  [126 115  71]]

 [[ 88  96  42]
  [ 90  96  41]
  [ 92  98  40]
  ...
  [120 112  66]
  [129 121  74]
  [124 117  67]]

 [[ 90  94  50]
  [ 90  94  46]
  [ 91  95  46]
  ...
  [ 68  54  26]
  [ 64  51  24]
  [ 64  55  21]]

 ...

 [[154 178 1

Face detected -- []
[[[ 85 104  43]
  [ 84 103  48]
  [ 95  93  49]
  ...
  [130 121  66]
  [120 117  71]
  [127 112  77]]

 [[ 86  96  34]
  [ 89  98  42]
  [ 88  97  42]
  ...
  [120 109  59]
  [133 123  70]
  [133 120  69]]

 [[ 78 100  46]
  [ 87  98  43]
  [ 90  96  43]
  ...
  [ 72  53  23]
  [ 66  49  13]
  [ 68  57  15]]

 ...

 [[149 176 117]
  [147 177 115]
  [141 171 114]
  ...
  [107 111 109]
  [108 112 108]
  [111 116 111]]

 [[154 174 109]
  [148 175 114]
  [145 172 112]
  ...
  [108 110 107]
  [105 109 106]
  [111 117 109]]

 [[144 179 114]
  [146 176 111]
  [147 175 111]
  ...
  [104 111 106]
  [101 107 104]
  [105 107 107]]]
Face detected -- []
[[[ 87 100  40]
  [ 84  96  47]
  [ 92  97  46]
  ...
  [135 119  72]
  [137 108  69]
  [125 110  67]]

 [[ 88  99  44]
  [ 89  99  46]
  [ 89  98  49]
  ...
  [119 108  61]
  [130 122  71]
  [123 118  66]]

 [[ 90  97  43]
  [ 91  96  42]
  [ 88  97  43]
  ...
  [ 63  46  20]
  [ 70  55  23]
  [ 70  59  21]]

 ...

 [[ 83  84  

[[[ 93  99  42]
  [ 90  96  43]
  [ 98  98  44]
  ...
  [125 121  78]
  [124 118  69]
  [126 116  68]]

 [[ 89  97  38]
  [ 90  98  42]
  [ 89  98  43]
  ...
  [115 111  64]
  [129 120  72]
  [126 114  72]]

 [[ 94  95  48]
  [ 91  96  39]
  [ 92  99  40]
  ...
  [ 60  52  25]
  [ 62  50  21]
  [ 71  54  17]]

 ...

 [[158 176 122]
  [154 179 118]
  [151 180 118]
  ...
  [131 103  83]
  [141 113  93]
  [152 125 103]]

 [[149 182 116]
  [150 177 117]
  [152 179 118]
  ...
  [122  93  73]
  [128 101  77]
  [139 114  83]]

 [[155 174 124]
  [151 175 120]
  [151 178 119]
  ...
  [106  79  61]
  [112  88  65]
  [125  96  76]]]
Face detected -- []
[[[ 93  99  42]
  [ 90  96  43]
  [ 98  98  44]
  ...
  [125 121  78]
  [124 118  69]
  [126 116  68]]

 [[ 89  97  38]
  [ 90  98  42]
  [ 89  98  43]
  ...
  [115 111  64]
  [129 120  72]
  [126 114  72]]

 [[ 94  95  48]
  [ 91  96  39]
  [ 92  99  40]
  ...
  [ 60  52  25]
  [ 62  50  21]
  [ 71  54  17]]

 ...

 [[158 176 122]
  [154 179 118]


[[[ 94  98  45]
  [ 87  98  47]
  [ 95  97  53]
  ...
  [133 114  72]
  [134 112  69]
  [127 114  72]]

 [[ 92  96  46]
  [ 92  98  46]
  [ 92  98  47]
  ...
  [118 108  64]
  [135 125  78]
  [127 114  75]]

 [[ 90  95  52]
  [ 91  96  51]
  [ 91  98  52]
  ...
  [ 62  53  27]
  [ 63  52  22]
  [ 74  59  24]]

 ...

 [[154 177 128]
  [152 176 126]
  [152 176 124]
  ...
  [115  85  72]
  [119  88  76]
  [129  96  81]]

 [[156 174 123]
  [150 177 123]
  [151 178 124]
  ...
  [ 98  69  58]
  [102  72  61]
  [110  81  66]]

 [[147 180 120]
  [149 178 125]
  [150 178 126]
  ...
  [ 89  61  46]
  [ 96  69  52]
  [100  71  53]]]
Face detected -- []
[[[ 80 103  46]
  [ 86 101  49]
  [ 88  97  55]
  ...
  [129 118  77]
  [127 117  63]
  [127 117  71]]

 [[ 92 103  45]
  [ 89  96  45]
  [ 91  98  49]
  ...
  [122 112  69]
  [133 122  77]
  [127 118  76]]

 [[ 88  99  50]
  [ 89  97  45]
  [ 88  96  46]
  ...
  [ 70  53  32]
  [ 68  52  29]
  [ 71  57  26]]

 ...

 [[154 177 130]
  [153 177 129]


Face detected -- []
[[[ 83 101  46]
  [ 92  96  47]
  [ 92  99  58]
  ...
  [135 121  80]
  [128 114  70]
  [128 111  75]]

 [[ 93  97  50]
  [ 88  97  51]
  [ 90  97  53]
  ...
  [118 109  68]
  [130 119  79]
  [128 112  76]]

 [[ 93  93  61]
  [ 90  95  55]
  [ 90  97  56]
  ...
  [ 66  53  28]
  [ 65  53  26]
  [ 69  58  30]]

 ...

 [[157 175 128]
  [155 179 132]
  [152 178 130]
  ...
  [118  90  76]
  [128  97  83]
  [139 112 100]]

 [[154 176 128]
  [152 178 129]
  [151 179 131]
  ...
  [102  76  61]
  [110  83  71]
  [123  95  85]]

 [[152 178 131]
  [151 176 127]
  [150 176 128]
  ...
  [ 92  69  57]
  [ 95  72  59]
  [104  82  62]]]
Face detected -- []
[[[ 95  95  56]
  [ 88 100  54]
  [ 94 101  60]
  ...
  [130 118  78]
  [123 117  76]
  [122 117  79]]

 [[ 93  98  48]
  [ 92  99  53]
  [ 91  99  54]
  ...
  [120 114  70]
  [128 121  80]
  [127 114  81]]

 [[ 85  97  60]
  [ 88  95  53]
  [ 89  95  54]
  ...
  [ 65  47  25]
  [ 69  48  28]
  [ 73  54  32]]

 ...

 [[150 176 1

Face detected -- []
[[[ 94  98  45]
  [ 89  96  51]
  [ 91  99  59]
  ...
  [129 122  79]
  [127 114  76]
  [126 110  81]]

 [[ 96  93  54]
  [ 90  95  55]
  [ 90  97  56]
  ...
  [120 110  67]
  [130 120  77]
  [131 114  82]]

 [[ 89  94  58]
  [ 89  96  55]
  [ 89  96  55]
  ...
  [ 65  51  28]
  [ 67  50  30]
  [ 73  51  34]]

 ...

 [[153 177 130]
  [156 180 132]
  [153 177 130]
  ...
  [136 106  94]
  [144 115 102]
  [148 121 110]]

 [[149 177 132]
  [152 176 129]
  [153 177 129]
  ...
  [124  95  84]
  [133 104  93]
  [145 114 100]]

 [[147 178 129]
  [150 178 128]
  [151 178 129]
  ...
  [112  81  73]
  [120  89  79]
  [129 102  89]]]
Face detected -- []
[[[ 95  97  51]
  [ 93  93  53]
  [ 90  99  59]
  ...
  [134 117  76]
  [133 112  74]
  [128 112  72]]

 [[ 92  94  49]
  [ 93  97  51]
  [ 94 100  57]
  ...
  [123 111  68]
  [132 118  75]
  [129 114  76]]

 [[ 93  93  59]
  [ 90  96  53]
  [ 90  97  56]
  ...
  [ 69  50  27]
  [ 69  47  26]
  [ 77  51  27]]

 ...

 [[155 179 1

Face detected -- []
[[[ 97  96  61]
  [104  88  59]
  [ 96  96  54]
  ...
  [128 117  76]
  [128 117  80]
  [135 114  73]]

 [[ 92  97  42]
  [ 91  98  53]
  [ 90  95  51]
  ...
  [118 108  69]
  [130 121  79]
  [125 115  74]]

 [[ 88  97  54]
  [ 90  97  53]
  [ 89  97  51]
  ...
  [ 69  51  35]
  [ 69  50  28]
  [ 70  55  30]]

 ...

 [[153 179 126]
  [153 180 131]
  [153 179 132]
  ...
  [109 108 116]
  [112 111 120]
  [116 115 130]]

 [[154 177 131]
  [150 179 129]
  [151 178 129]
  ...
  [105 106 114]
  [107 106 114]
  [110 111 120]]

 [[154 179 129]
  [148 176 128]
  [150 178 130]
  ...
  [103 112 111]
  [111 111 114]
  [113 109 118]]]
Face detected -- []
[[[ 89 101  57]
  [ 93  95  60]
  [ 93  95  63]
  ...
  [131 119  81]
  [131 116  79]
  [128 118  78]]

 [[ 87  95  60]
  [ 89  95  55]
  [ 91  95  54]
  ...
  [120 110  71]
  [133 126  82]
  [127 118  73]]

 [[ 88  96  61]
  [ 89  96  55]
  [ 89  96  55]
  ...
  [ 66  50  30]
  [ 67  53  30]
  [ 71  58  32]]

 ...

 [[156 180 1

Face detected -- []
[[[ 88  97  57]
  [ 87  96  56]
  [ 93  96  50]
  ...
  [139 111  79]
  [131 115  76]
  [122 118  75]]

 [[101  88  55]
  [ 92  97  55]
  [ 90  97  56]
  ...
  [122 111  71]
  [133 124  84]
  [123 116  77]]

 [[ 90  95  54]
  [ 88  95  52]
  [ 90  98  56]
  ...
  [ 64  47  29]
  [ 71  50  31]
  [ 76  54  30]]

 ...

 [[154 179 126]
  [150 179 130]
  [149 178 129]
  ...
  [107 106 116]
  [108 109 117]
  [112 116 123]]

 [[151 180 131]
  [151 176 128]
  [153 177 128]
  ...
  [108 107 118]
  [107 108 116]
  [112 108 118]]

 [[155 176 125]
  [152 176 126]
  [154 180 130]
  ...
  [110 108 116]
  [108 109 112]
  [113 115 119]]]
Face detected -- []
[[[ 94  91  53]
  [ 92  93  61]
  [ 90 101  57]
  ...
  [129 117  87]
  [125 115  78]
  [127 113  73]]

 [[ 91  94  58]
  [ 90  97  55]
  [ 91  96  51]
  ...
  [119 106  69]
  [128 119  77]
  [122 119  78]]

 [[ 87  95  60]
  [ 89  97  54]
  [ 90  97  53]
  ...
  [ 67  52  31]
  [ 69  52  31]
  [ 70  55  37]]

 ...

 [[149 176 1

Face detected -- []
[[[ 89  94  58]
  [ 99  94  60]
  [ 87  98  58]
  ...
  [130 120  82]
  [131 111  73]
  [120 116  82]]

 [[ 91  93  52]
  [ 91  95  51]
  [ 89  96  53]
  ...
  [119 108  69]
  [131 119  79]
  [129 116  77]]

 [[ 90  97  56]
  [ 92  96  53]
  [ 91  96  55]
  ...
  [ 69  52  35]
  [ 71  53  35]
  [ 74  49  37]]

 ...

 [[150 177 130]
  [154 178 132]
  [157 180 133]
  ...
  [ 78  78  80]
  [ 84  84  89]
  [ 97  96 103]]

 [[157 174 131]
  [155 178 133]
  [153 177 130]
  ...
  [ 74  78  78]
  [ 79  85  85]
  [ 92  96  98]]

 [[154 178 130]
  [153 179 131]
  [153 178 130]
  ...
  [ 79  81  81]
  [ 79  83  86]
  [ 91  94 103]]]
Face detected -- []
[[[ 95  99  50]
  [ 85  98  57]
  [ 96  97  55]
  ...
  [129 115  73]
  [127 112  78]
  [127 114  74]]

 [[ 95  93  60]
  [ 92  95  56]
  [ 90  95  55]
  ...
  [121 108  72]
  [130 119  79]
  [129 116  74]]

 [[ 96  94  53]
  [ 95  97  55]
  [ 91  95  54]
  ...
  [ 70  49  35]
  [ 66  49  32]
  [ 72  58  29]]

 ...

 [[154 176 1

Face detected -- []
[[[ 91  96  53]
  [ 97  97  55]
  [ 88  98  54]
  ...
  [197 186 135]
  [114 104  82]
  [117 120 102]]

 [[ 87  97  59]
  [ 89  96  54]
  [ 90  97  56]
  ...
  [143 149 126]
  [104 103  82]
  [ 95  89  68]]

 [[ 88  95  51]
  [ 88  97  52]
  [ 89  97  51]
  ...
  [126 123 103]
  [116 109  91]
  [106  95  78]]

 ...

 [[154 177 125]
  [150 176 128]
  [149 174 127]
  ...
  [ 35  38  56]
  [ 39  36  60]
  [ 45  31  63]]

 [[148 182 125]
  [150 175 123]
  [152 176 128]
  ...
  [ 36  40  58]
  [ 35  38  59]
  [ 38  29  59]]

 [[149 178 129]
  [148 174 126]
  [151 175 127]
  ...
  [ 31  37  48]
  [ 23  29  44]
  [ 21  34  49]]]
Face detected -- []
[[[ 92  98  54]
  [ 89  99  49]
  [ 97  98  53]
  ...
  [160 153 128]
  [131 132  93]
  [132 115  81]]

 [[ 92  94  59]
  [ 90  96  52]
  [ 92  96  50]
  ...
  [123 117  87]
  [130 129  96]
  [123 122  95]]

 [[ 86  98  53]
  [ 87  96  54]
  [ 90  97  54]
  ...
  [ 95  91  73]
  [ 85  77  61]
  [ 81  72  56]]

 ...

 [[122 148 1

Face detected -- []
[[[ 88 100  53]
  [ 91  96  58]
  [ 97  97  64]
  ...
  [141 114  78]
  [124 113  71]
  [125 115  78]]

 [[ 89  99  58]
  [ 94 100  58]
  [ 93 100  56]
  ...
  [120 110  71]
  [130 123  79]
  [122 115  73]]

 [[ 96  92  57]
  [ 91  96  56]
  [ 90  97  57]
  ...
  [ 61  46  29]
  [ 62  47  27]
  [ 65  56  28]]

 ...

 [[152 177 137]
  [155 178 132]
  [156 178 132]
  ...
  [117 119 124]
  [124 122 128]
  [127 123 136]]

 [[154 178 130]
  [151 178 130]
  [154 178 131]
  ...
  [119 118 123]
  [124 123 128]
  [125 127 132]]

 [[154 178 133]
  [151 178 130]
  [154 178 134]
  ...
  [114 119 124]
  [118 124 127]
  [123 129 130]]]
Face detected -- []
[[[ 86  95  59]
  [ 94  98  58]
  [ 90 102  54]
  ...
  [132 120  73]
  [123 114  79]
  [131 112  78]]

 [[ 87  96  57]
  [ 91  98  54]
  [ 90  98  57]
  ...
  [121 110  69]
  [131 120  77]
  [128 115  74]]

 [[ 87  97  51]
  [ 90  99  55]
  [ 89  99  57]
  ...
  [ 65  54  27]
  [ 67  52  23]
  [ 75  54  26]]

 ...

 [[158 177 1

Face detected -- ['guru prakash']
[[[ 88  98  89]
  [ 88  95  84]
  [ 94  95  84]
  ...
  [130 119 106]
  [122 119 105]
  [127 114 106]]

 [[ 87  94  84]
  [ 87  97  82]
  [ 88  98  82]
  ...
  [133 126 111]
  [125 120 104]
  [123 121 107]]

 [[ 92  94  84]
  [ 86  97  83]
  [ 86  98  84]
  ...
  [ 69  49  57]
  [ 76  59  65]
  [ 93  82  80]]

 ...

 [[153 176 159]
  [151 176 162]
  [150 176 166]
  ...
  [ 81  76  83]
  [ 79  71  63]
  [ 79  75  57]]

 [[152 171 163]
  [151 177 162]
  [150 177 164]
  ...
  [ 95  96 114]
  [ 76  76  74]
  [ 75  75  60]]

 [[150 178 166]
  [147 178 163]
  [149 178 166]
  ...
  [119 128 152]
  [ 78  81  86]
  [ 75  78  62]]]
Face detected -- ['guru prakash']
[[[ 84 102  88]
  [ 86 101  89]
  [ 92  90  86]
  ...
  [128 119 105]
  [124 119 105]
  [124 116 103]]

 [[ 86 101  82]
  [ 92  96  80]
  [ 92  94  80]
  ...
  [130 125 111]
  [123 117 104]
  [126 119 107]]

 [[ 88 100  83]
  [ 90  93  83]
  [ 91  93  87]
  ...
  [ 65  57  58]
  [ 76  64  66]
  [ 93  

[[[ 97  96  84]
  [ 91  97  90]
  [ 97  93  91]
  ...
  [130 114 111]
  [127 116 104]
  [129 111 114]]

 [[ 98  93  94]
  [ 93  93  89]
  [ 90  93  84]
  ...
  [136 124 113]
  [132 121 110]
  [127 119 109]]

 [[ 95  91  86]
  [ 94  95  87]
  [ 90  97  84]
  ...
  [ 71  58  58]
  [ 77  62  63]
  [ 95  78  85]]

 ...

 [[152 171 174]
  [149 176 168]
  [148 178 168]
  ...
  [ 75  69  51]
  [ 73  71  51]
  [ 68  74  53]]

 [[144 175 173]
  [148 176 167]
  [149 176 165]
  ...
  [ 79  69  52]
  [ 73  72  48]
  [ 70  74  48]]

 [[148 174 168]
  [150 176 166]
  [151 175 167]
  ...
  [ 74  69  52]
  [ 72  69  46]
  [ 76  67  46]]]
Face detected -- []
[[[ 91  99  90]
  [ 89  96  83]
  [ 96  93  87]
  ...
  [130 115 111]
  [131 118 108]
  [129 109 110]]

 [[ 94  92  78]
  [ 89  95  82]
  [ 90  95  86]
  ...
  [134 123 113]
  [129 116 107]
  [130 114 109]]

 [[ 93  94  92]
  [ 91  90  86]
  [ 90  91  86]
  ...
  [ 73  53  58]
  [ 83  67  69]
  [ 98  85  89]]

 ...

 [[152 173 172]
  [153 176 169]


Face detected -- []
[[[ 92  93  88]
  [ 91  93  87]
  [ 90  98  80]
  ...
  [134 112 118]
  [129 114 114]
  [131 110 118]]

 [[ 89  96  78]
  [ 90  99  87]
  [ 88  96  86]
  ...
  [135 120 115]
  [132 116 111]
  [133 115 115]]

 [[ 90  91  90]
  [ 88  96  84]
  [ 86  97  84]
  ...
  [ 71  51  62]
  [ 77  62  68]
  [ 96  84  79]]

 ...

 [[152 171 166]
  [152 174 167]
  [151 175 167]
  ...
  [ 75  72  49]
  [ 75  76  54]
  [ 71  71  57]]

 [[144 172 165]
  [150 177 168]
  [151 176 168]
  ...
  [ 72  72  49]
  [ 76  75  54]
  [ 70  72  52]]

 [[144 177 168]
  [146 178 167]
  [145 177 168]
  ...
  [ 77  67  43]
  [ 77  68  47]
  [ 79  70  54]]]
Face detected -- []
[[[ 93  97  86]
  [ 91  99  87]
  [ 87  96  89]
  ...
  [130 118 106]
  [131 112 114]
  [131 112 115]]

 [[ 86  96  90]
  [ 85  96  85]
  [ 90 100  90]
  ...
  [132 123 112]
  [130 118 113]
  [131 113 117]]

 [[ 88  95  81]
  [ 91  96  87]
  [ 90  95  85]
  ...
  [ 67  56  58]
  [ 76  65  67]
  [ 94  78  82]]

 ...

 [[146 175 1

[[[ 83 100  84]
  [ 91  97  85]
  [ 93  97  91]
  ...
  [142 121 123]
  [137 120 127]
  [121  98 115]]

 [[ 91  92  89]
  [ 90  94  87]
  [ 91  96  89]
  ...
  [134 115 109]
  [130 112 106]
  [121 104  99]]

 [[101  93  86]
  [ 92  92  84]
  [ 93  93  88]
  ...
  [111  97  98]
  [119 106 103]
  [113 104  97]]

 ...

 [[154 173 170]
  [153 174 167]
  [154 175 168]
  ...
  [114 110 165]
  [119 118 167]
  [124 124 164]]

 [[154 174 161]
  [154 176 167]
  [154 176 167]
  ...
  [118 114 166]
  [116 114 164]
  [123 126 169]]

 [[155 173 163]
  [155 177 166]
  [154 176 166]
  ...
  [117 112 158]
  [115 113 158]
  [114 117 163]]]
Face detected -- ['guru prakash']
[[[ 88  98  79]
  [ 97  97  84]
  [ 97  95  93]
  ...
  [141 119 118]
  [135 124 116]
  [120 107 112]]

 [[ 93  95  83]
  [ 93  95  80]
  [ 94  96  83]
  ...
  [132 115 109]
  [130 112 109]
  [121 103 101]]

 [[ 98  87  83]
  [ 93  92  84]
  [ 92  91  86]
  ...
  [109  93  91]
  [119 104 100]
  [119 101  93]]

 ...

 [[154 174 170]
  

Face detected -- ['guru prakash']
